# Generated by Django 4.2.6 on 2023-11-25 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_reviews', '0001_initial_squashed_0002_userprofile_follows_alter_book_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='answered',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='response',
        ),
        migrations.AddField(
            model_name='review',
            name='ticket',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='review',
                to='books_reviews.ticket'
            ),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(
                upload_to='books_reviews/static/books_reviews/uploads/%Y/%m/%d/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['png', 'jpeg', 'jpg']
                    )
                ]
            ),
        ),
    ]
